#!/usr/bin/env python3
"""Summarize scene candidate counts from the candidate CSV.

This script is intentionally read-only for the candidate file. It creates a
separate summary CSV so report numbers can be refreshed without hardcoding.
"""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_INPUT = Path("KAPAL YG TERDETEKSI/scene_candidates_godark_spoofing_transshipment.csv")
DEFAULT_OUTPUT = Path("KAPAL YG TERDETEKSI/scene_candidates_summary.csv")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Candidate CSV generated by find-scene-candidates.py.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Summary CSV path.")
    parser.add_argument("--candidate-column", default="candidate_type", help="Column containing candidate labels.")
    return parser.parse_args()


def read_candidate_counts(path: Path, candidate_column: str) -> tuple[Counter[str], int]:
    if not path.exists():
        raise FileNotFoundError(f"Candidate CSV not found: {path}")

    counts: Counter[str] = Counter()
    total = 0
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            raise ValueError(f"Candidate CSV has no header: {path}")
        if candidate_column not in reader.fieldnames:
            columns = ", ".join(reader.fieldnames)
            raise ValueError(f"Column '{candidate_column}' not found in {path}. Available columns: {columns}")

        for row in reader:
            label = str(row.get(candidate_column, "")).strip()
            if not label:
                label = "(blank)"
            counts[label] += 1
            total += 1
    return counts, total


def write_summary(path: Path, counts: Counter[str], total: int, source: Path, candidate_column: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    rows = []
    for label, count in sorted(counts.items(), key=lambda item: (-item[1], item[0])):
        percentage = (count / total * 100.0) if total else 0.0
        rows.append(
            {
                "candidate_type": label,
                "count": str(count),
                "percentage": f"{percentage:.2f}",
                "total_candidates": str(total),
                "candidate_column": candidate_column,
                "source_file": str(source),
                "generated_at_utc": generated_at,
            }
        )

    if not rows:
        rows.append(
            {
                "candidate_type": "(none)",
                "count": "0",
                "percentage": "0.00",
                "total_candidates": "0",
                "candidate_column": candidate_column,
                "source_file": str(source),
                "generated_at_utc": generated_at,
            }
        )

    fieldnames = [
        "candidate_type",
        "count",
        "percentage",
        "total_candidates",
        "candidate_column",
        "source_file",
        "generated_at_utc",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def print_summary(counts: Counter[str], total: int, output: Path) -> None:
    print(f"Total candidates: {total}")
    if not counts:
        print("No candidates found.")
    else:
        for label, count in sorted(counts.items(), key=lambda item: (-item[1], item[0])):
            percentage = (count / total * 100.0) if total else 0.0
            print(f"{label}: {count} ({percentage:.2f}%)")
    print(f"Summary CSV: {output}")


def main() -> None:
    args = parse_args()
    counts, total = read_candidate_counts(args.input, args.candidate_column)
    write_summary(args.output, counts, total, args.input, args.candidate_column)
    print_summary(counts, total, args.output)


if __name__ == "__main__":
    main()
